### ISSUE TITLE
Investigate failures under HHVM

### ISSUE THREAD

**Issue by ezzatron** [peridot-php/leo#27]
Currently, some specs are causing errors like the following under HHVM:

```
  1) assert ->doesNotThrow() should throw an exception if function throws exception:
     print_r() exceeded max bytes limit
      #0 (): Closure$Peridot\Core\Test::handleErrors()
      #1 /home/travis/build/peridot-php/leo/src/Formatter/Formatter.php(91): print_r()
      #2 /home/travis/build/peridot-php/leo/src/Formatter/Formatter.php(61): Peridot\Leo\Formatter\Formatter->objectToString()
      #3 /home/travis/build/peridot-php/leo/src/Responder/ExceptionResponder.php(49): Peridot\Leo\Formatter\Formatter->getMessage()
      #4 /home/travis/build/peridot-php/leo/src/Assertion.php(224): Peridot\Leo\Responder\ExceptionResponder->respond()
      #5 /home/travis/build/peridot-php/leo/src/Assertion.php(156): Peridot\Leo\Assertion->assert()
      #6 /home/travis/build/peridot-php/leo/src/Assertion.php(117): Peridot\Leo\Assertion->request()
      #7 /home/travis/build/peridot-php/leo/src/Interfaces/Assert.php(109): Peridot\Leo\Assertion->__call()
      #8 /home/travis/build/peridot-php/leo/specs/interfaces/assert.spec.php(74): Peridot\Leo\Interfaces\Assert->doesNotThrow()
      #9 (): Closure$#24()
      #10 /home/travis/build/peridot-php/leo/src/Matcher/ExceptionMatcher.php(206): call_user_func_array()
      #11 /home/travis/build/peridot-php/leo/src/Matcher/AbstractMatcher.php(71): Peridot\Leo\Matcher\ExceptionMatcher->doMatch()
      #12 /home/travis/build/peridot-php/leo/src/Matcher/ExceptionMatcher.php(188): Peridot\Leo\Matcher\AbstractMatcher->match()
      #13 /home/travis/build/peridot-php/leo/src/Assertion.php(218): Peridot\Leo\Matcher\ExceptionMatcher->match()
      #14 /home/travis/build/peridot-php/leo/src/Assertion.php(156): Peridot\Leo\Assertion->assert()
      #15 /home/travis/build/peridot-php/leo/src/Assertion.php(117): Peridot\Leo\Assertion->request()
      #16 /home/travis/build/peridot-php/leo/src/Interfaces/Assert.php(95): Peridot\Leo\Assertion->__call()
      #17 /home/travis/build/peridot-php/leo/specs/interfaces/assert.spec.php(75): Peridot\Leo\Interfaces\Assert->throws()
      #18 (): Closure$#25()
      #19 /home/travis/build/peridot-php/leo/vendor/peridot-php/peridot/src/Core/Test.php(61): call_user_func_array()
      #20 /home/travis/build/peridot-php/leo/vendor/peridot-php/peridot/src/Core/Test.php(46): Peridot\Core\Test->executeTest()
      #21 /home/travis/build/peridot-php/leo/vendor/peridot-php/peridot/src/Core/Suite.php(112): Peridot\Core\Test->run()
      #22 /home/travis/build/peridot-php/leo/vendor/peridot-php/peridot/src/Core/Suite.php(83): Peridot\Core\Suite->runTest()
      #23 /home/travis/build/peridot-php/leo/vendor/peridot-php/peridot/src/Core/Suite.php(112): Peridot\Core\Suite->run()
      #24 /home/travis/build/peridot-php/leo/vendor/peridot-php/peridot/src/Core/Suite.php(83): Peridot\Core\Suite->runTest()
      #25 /home/travis/build/peridot-php/leo/vendor/peridot-php/peridot/src/Core/Suite.php(112): Peridot\Core\Suite->run()
      #26 /home/travis/build/peridot-php/leo/vendor/peridot-php/peridot/src/Core/Suite.php(83): Peridot\Core\Suite->runTest()
      #27 /home/travis/build/peridot-php/leo/vendor/peridot-php/peridot/src/Runner/Runner.php(57): Peridot\Core\Suite->run()
      #28 /home/travis/build/peridot-php/leo/vendor/peridot-php/peridot/src/Console/Command.php(176): Peridot\Runner\Runner->run()
      #29 /home/travis/build/peridot-php/leo/vendor/peridot-php/peridot/src/Console/Command.php(149): Peridot\Console\Command->getResult()
      #30 /home/travis/build/peridot-php/leo/vendor/symfony/console/Command/Command.php(259): Peridot\Console\Command->execute()
      #31 /home/travis/build/peridot-php/leo/vendor/symfony/console/Application.php(847): Symfony\Component\Console\Command\Command->run()
      #32 /home/travis/build/peridot-php/leo/vendor/symfony/console/Application.php(192): Symfony\Component\Console\Application->doRunCommand()
      #33 /home/travis/build/peridot-php/leo/vendor/peridot-php/peridot/src/Console/Application.php(84): Symfony\Component\Console\Application->doRun()
      #34 /home/travis/build/peridot-php/leo/vendor/symfony/console/Application.php(123): Peridot\Console\Application->doRun()
      #35 /home/travis/build/peridot-php/leo/vendor/peridot-php/peridot/src/Console/Application.php(63): Symfony\Component\Console\Application->run()
      #36 /home/travis/build/peridot-php/leo/vendor/peridot-php/peridot/bin/peridot(45): Peridot\Console\Application->run()
      #37 {main}
```

I'm going to shift the HHVM builds to the "allowed failures" section to get this round of repo maintenance done, but these errors should be addressed properly ASAP.

**Comment by ezzatron** [comment]
This is a duplicate of #15, which is closed for some reason.

**Comment by ezzatron** [comment]
Also relates to #9.

**Comment by ragboyjr** [comment]
Considering that hhvm is now diverging from PHP, supporting HHVM doesn't seem viable. I'm most likely just going to drop hhvm support.
